build: off
clone_depth: 1
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"

platform:
  - x86
  - x64

install:
  - cmd: git submodule update --init --recursive
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: qio platform install file://.

test_script:
  - cmd: qio run -d "examples/hello"
