build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/hello"

install:
  - cmd: git submodule update --init --recursive
  - cmd: python -m pip install --upgrade pip
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: qio platform install file://.

test_script:
  - cmd: qio run -d %PLATFORMIO_PROJECT_DIR%
